src/Entity/Pets.php
<?php

namespace App\Entity;

use App\Repository\PetsRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=PetsRepository::class)
 */
class Pets
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="integer")
     */
    private $pet_type_id;

    /**
     * @ORM\Column(type="integer")
     */
    private $gender;

    /**
     * @ORM\Column(type="integer")
     */
    private $breed_id;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="integer")
     */
    private $age;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $client_id;

    /**
     * @ORM\ManyToOne(targetEntity=Clients::class, inversedBy="client_id")
     */
    private $client_id_relation;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPetTypeId(): ?int
    {
        return $this->pet_type_id;
    }

    public function setPetTypeId(int $pet_type_id): self
    {
        $this->pet_type_id = $pet_type_id;

        return $this;
    }

    public function getGender(): ?int
    {
        return $this->gender;
    }

    public function setGender(int $gender): self
    {
        $this->gender = $gender;

        return $this;
    }

    public function getBreedId(): ?int
    {
        return $this->breed_id;
    }

    public function setBreedId(int $breed_id): self
    {
        $this->breed_id = $breed_id;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getAge(): ?int
    {
        return $this->age;
    }

    public function setAge(int $age): self
    {
        $this->age = $age;

        return $this;
    }

    public function getClientId(): ?int
    {
        return $this->client_id;
    }

    public function setClientId(?int $client_id): self
    {
        $this->client_id = $client_id;

        return $this;
    }

    public function getClientIdRelation(): ?Clients
    {
        return $this->client_id_relation;
    }

    public function setClientIdRelation(?Clients $client_id_relation): self
    {
        $this->client_id_relation = $client_id_relation;

        return $this;
    }
}

src/Form/PetsType.php
<?php

namespace App\Form;

use App\Entity\Pets;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PetsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('pet_type_id')
            ->add('gender')
            ->add('breed_id')
            ->add('image')
            ->add('age')
            ->add('client_id')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Pets::class,
        ]);
    }
}

src/Controller/PetsController.php
<?php

namespace App\Controller;

use App\Entity\Pets;
use App\Form\PetsType;
use App\Repository\PetsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/pets")
 */
class PetsController extends AbstractController
{
    /**
     * @Route("/", name="pets_index", methods={"GET"})
     */
    public function index(PetsRepository $petsRepository): Response
    {
        return $this->render('pets/index.html.twig', [
            'pets' => $petsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="pets_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $pet = new Pets();
        $form = $this->createForm(PetsType::class, $pet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($pet);
            $entityManager->flush();

            return $this->redirectToRoute('pets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pets/new.html.twig', [
            'pet' => $pet,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="pets_show", methods={"GET"})
     */
    public function show(Pets $pet): Response
    {
        return $this->render('pets/show.html.twig', [
            'pet' => $pet,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="pets_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Pets $pet): Response
    {
        $form = $this->createForm(PetsType::class, $pet);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('pets_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('pets/edit.html.twig', [
            'pet' => $pet,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="pets_delete", methods={"POST"})
     */
    public function delete(Request $request, Pets $pet): Response
    {
        if ($this->isCsrfTokenValid('delete'.$pet->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($pet);
            $entityManager->flush();
        }

        return $this->redirectToRoute('pets_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/pets/_delete_form.html.twig
<form method="post" action="{{ path('pets_delete', {'id': pet.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ pet.id) }}">
    <button class="btn">Delete</button>
</form>

templates/pets/_form.html.twig
{% form_theme form 'bootstrap_5_layout.html.twig' %}
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/pets/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Редактирование данны питомца{% endblock %}

{% block body %}
    <h1>Редактирование данны питомца</h1>

    {{ include('pets/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('pets_index') }}">back to list</a>

    {{ include('pets/_delete_form.html.twig') }}
{% endblock %}

templates/pets/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Pets index{% endblock %}

{% block body %}
    <h1>Список питомцев</h1>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Кличка</th>
                <th>Тип животного</th>
                <th>Пол</th>
                <th>Порода</th>
                <th>Фото</th>
                <th>Возвраст</th>
                <th>Хозяин</th>
                <th>Действия</th>
            </tr>
        </thead>
        <tbody>
        {% for pet in pets %}
            <tr>
                <td>{{ pet.id }}</td>
                <td>{{ pet.name }}</td>
                <td>{{ pet.petTypeId }}</td>
                <td>{{ pet.gender }}</td>
                <td>{{ pet.breedId }}</td>
                <td>{{ pet.image }}</td>
                <td>{{ pet.age }}</td>
                <td>{{ pet.clientId }}</td>
                <td>
                    <a href="{{ path('pets_show', {'id': pet.id}) }}">show</a>
                    <a href="{{ path('pets_edit', {'id': pet.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="9">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('pets_new') }}">Добавить питомца</a>
{% endblock %}

templates/pets/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавление нового питомца{% endblock %}

{% block body %}
    <h1>Добавление нового питомца</h1>

    {{ include('pets/_form.html.twig') }}

    <a href="{{ path('pets_index') }}">back to list</a>
{% endblock %}

templates/pets/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Питомец <b>{{ pet.name }}</b>{% endblock %}

{% block body %}
    <h1>Питомец <b>{{ pet.name }}</b></h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ pet.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ pet.name }}</td>
            </tr>
            <tr>
                <th>Pet_type_id</th>
                <td>{{ pet.petTypeId }}</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>{{ pet.gender }}</td>
            </tr>
            <tr>
                <th>Breed_id</th>
                <td>{{ pet.breedId }}</td>
            </tr>
            <tr>
                <th>Image</th>
                <td>{{ pet.image }}</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>{{ pet.age }}</td>
            </tr>
            <tr>
                <th>Client_id</th>
                <td>{{ pet.clientId }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('pets_index') }}">back to list</a>

    <a href="{{ path('pets_edit', {'id': pet.id}) }}">edit</a>

    {{ include('pets/_delete_form.html.twig') }}
{% endblock %}